version: "3"

services:
  node:
    # Imagem base do container
    image: node:16
    # Nome do container para facilitar execução
    container_name: uaifood
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    # Substitui o comando padrão da imagem do node
    command: bash
    # Restarta a imagem caso algo a faça parar
    restart: always
    # Diretório padrão de execução
    working_dir: /app
    # Lista de volumes (diretórios) mapeados de fora para dentro do container
    volumes:
      # Monta o diretório atual, com todos os dados do projeto, 
      # dentro do diretório /app
      - ./:/usr/app
    # Lista de portas mapeadas de dentro para fora do container
    # na notação porta_de_fora:porta_de_dentro
    ports:
      # Expõe a porta padrão da aplicação: altere aqui caso use outra porta
      - 3000:3000

  # Serviço que irá rodar o banco de dados
  database:
    # Imagem do dockerfile
    image: ./db
    ports:
      - "3306:3036"
    # variáveis de ambiente para acesso ao banco de dados
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uaifood
      MYSQL_USER: root
      MYSQL_PASSWORD: root

networks:
  default:
    name: uaifood_net

# A renomeação da rede padrão é feita pois caso contrário o nome da rede será
# o nome do diretório onde o arquivo atual se encontra, o que pode dificultar
# a listagem individual.